insert into alien values(1,'ruchita','java')
insert into alien values(2,'rachit','management')
insert into alien  values(3,'rohit','salesforce')
insert into alien   values(4,'priyanka','java')
insert into alien  values(5,'komal','javascript')